### ISSUE TITLE
Area: Check value of properties

### ISSUE THREAD

**Issue by ghost** [TeleMidia-MA/sncl#2]
* begin, end: 
   - Can be defined as "XX.Xs", or as "Hour":"Minute":"Second"."Fraction"
   - Hour is an natural in the range [0, 23]
   - Minute and Second is in the range [0, 59]
   - Fraction is any natural number
* first, last:
   - Can be defined as "XXf", "XXs", "XXnpt"
* coords:
   - Can be defined as "X1, Y1, X2, Y2,...,Xn, Yn"

**Comment by robertogerson** [comment]
Maybe, we should think in adding a native typing system for all the properties in the future.  For instance, I would prefer to write
```
media m1
  left: 10px
  explicitDur: 5s
  someStringProperty: "string"
end
```

instead of: 
```
media m1
  left: "10px"
  explicitDur: "5s"
  someStringProperty: "string"
end
```
In any case, it is easy to validate the properties using a regex approach.  Maybe, the regex defined by the ncl language model defined by the validator plugin could be useful for it (see the DATATYPE instructions):

https://github.com/TeleMidia/nclcomposer/blob/master/src/plugins/common-resources/config/NCL_STRUCTURE
